image: node:12

before_script:
  - npm ci

#cache:
#  paths:
#    - node_modules/

test:lint:
  script:
    - npm run lint

# LTS
test:node:12:
  script:
    - npm run clean
    - npm run build
    - npm run build:dist:dev
    - npm run build:dist:prod
    - npm test

test:node:11:
  image: node:11
  script:
    - npm run clean
    - npm run build
    - npm run build:dist:dev
    - npm run build:dist:prod
    - npm test

# LTS
test:node:10:
  image: node:10
  script:
    - npm run clean
    - npm run build
    - npm run build:dist:dev
    - npm run build:dist:prod
    - npm test

# LTS
test:node:8:
  image: node:8
  script:
    - npm run clean
    - npm run build
    - npm run build:dist:dev
    - npm run build:dist:prod
    - npm test

publish:artifacts:
  stage: deploy
#  only:
#    - tags
#    - triggers
  script:
    - npm run clean
    - npm run build:dist:dev
    - npm run build:dist:prod
  artifacts:
    paths:
      - dist/
